drop table if exists MATRICULA;
CREATE TABLE pruebaconexionbd.MATRICULA (
	ID INT NULL,
	CODIGO VARCHAR(8) NULL,
	CURSO INT(4) NULL,
	NOTA DECIMAL(4, 2) NULL,
	CONSTRAINT MATRICULA_pk PRIMARY KEY (ID,CODIGO, CURSO),
	CONSTRAINT MATRICULA_FK FOREIGN KEY (ID) REFERENCES pruebaconexionbd.alumno(id),
	CONSTRAINT MATRICULA_FK_1 FOREIGN KEY (CODIGO) REFERENCES pruebaconexionbd.MODULO(CODIGO)
);